File "./output/bug_15106.v", line 7, characters 0-18:
The command has indeed failed with message:
Obligation 2 already solved.
